-------Exploratry data Analysis (EDA)
--
--1.Explore All Objects in the Database
select
	*
from
	information_schema."tables" 
;
--2.Explore All Columns in the Database
select
	*
from
	information_schema.columns
where
	table_name = 'customers'
;
--3.Explore All Countries our customers come from.
select
	distinct
ct.country
from
	gold.customers ct 
;
--4.Explore All Categories "The major Divisions"
select
	distinct 
pd.category,
	pd.subcategory,
	pd.product_name
from
	gold.products pd
order by
	1,
	2,
	3
;
--5.Find the date of the first and last order
select
	min(sal.order_date) as First_order,
	max(sal.order_date) as last_order
from
	gold.sales sal
;
--6.How many years of sales are avaiable
select
	min(sl.order_date) as First_order,
	max(sl.order_date) as last_order,
	extract (year
from
	age(max(sl.order_date), min(sl.order_date))) as total_age
from
	gold.sales sl 
;
--7.Find the youngest and the oldest customer
select
	min(ct.birthdate) as oldest_customer,
	extract (year
from
	age(min(ct.birthdate))) as oldest_age,
	max(ct.birthdate) as younest_customer,
	extract (year
from
	age(max(ct.birthdate))) as younest_age
from
	gold.customers ct
;
--8.Find the Total Sales
select
	sum(sl.sales_amount) as total_sales
from
	gold.sales sl
;
--9.Find how many items are sold
select
	count(sl.quantity) total_quantity
from
	gold.sales sl
;
--10.Find the average selling price
select
	avg(sl.sales_amount) as avg_price
from
	gold.sales sl
;
--11.Find the Total number of Orders
select
	count(distinct sl.order_number)
from
	gold.sales sl
;

select
	count(distinct sl.customer_key) as total_order
from
	gold.sales sl
;
--12.Find the total number of products 

select
	count(pd.product_key) as total_product
from
	gold.products pd
;
--13.Find the total number of customers
select
	count(ct.customer_key) as total_customer
from
	gold.customers ct
;
--14.Find the total number of customers that has placed an order
select
	count(distinct sl.customer_key) as total_customer
from
	gold.sales sl
;
-------Generate a Report that shows all key metrics of the business

select
	'total_sales' as measure_names,
	sum(sl.sales_amount) as measure_values
from
	gold.sales sl
union all
select
	'total_quantity' as measure_names,
	count(sl.quantity) measure_values
from
	gold.sales sl
union all
select
	'avarage_price' as measure_names,
	avg(sl.sales_amount) as measure_values
from
	gold.sales sl
union all
select
	'total_orders' as measure_names,
	count(distinct sl.customer_key) as measure_values
from
	gold.sales sl
union all
select
	'total_products' as measure_names,
	count(pd.product_key) as measure_values
from
	gold.products pd
union all
select
	'total_customers' as measure_names,
	count(ct.customer_key) as measure_values
from
	gold.customers ct
;
--15.Find total customers by countries
select
	ct.country,
	count(ct.customer_key) as total_customer
from
	gold.customers ct
group by
	1
order by
	total_customer desc
;
--16.Find total customers by gender
select
	ct.gender,
	count(ct.customer_key) as total_customer
from
	gold.customers ct
group by
	1
order by
	total_customer desc
;
--17.Find total products by category
select
	pd.category,
	count(pd.product_name) as total_product
from
	gold.products pd
group by
	1
order by
	total_product desc
;
--18.What is the average costs in each category?
select
	pd.category,
	avg(pd."cost") as avg_cost
from
	gold.products pd
group by
	1
order by
	avg_cost desc
;
--19.What is the total revenue generated for each category?
select
	pd.category,
	sum(sl.sales_amount) as total_revenue
from
	gold.products pd
left join 
gold.sales sl
on
	pd.product_key = sl.product_key
group by
	1
order by
	total_revenue desc
;
--20.Find total revenue is generated by each customer
select
	ct.customer_key,
	ct.first_name,
	ct.last_name,
	sum(sl.sales_amount) as total_revenue
from
	gold.customers ct
left join 
gold.sales sl
on
	ct.customer_key = sl.customer_key
group by
	1,
	2,
	3
order by
	total_revenue desc
;
--21.What is the distribution of sold items across countries?
select
	ct.country,
	count(sl.quantity) as sold_item_qty
from
	gold.customers ct
left join 
gold.sales sl
on
	ct.customer_key = sl.customer_key
group by
	1
order by
	sold_item_qty desc
;
--22.Which 5 products generate the highest revenue?
select
	pd.product_name,
	sum(sl.sales_amount) as total_revenue
from
	gold.sales sl
left join 
gold.products pd 
on
	sl.product_key = pd.product_key
group by
	1
order by
	total_revenue desc
limit 5
;

select
	*
from
	(
	select
		pd.product_name,
		sum(sl.sales_amount) as total_revenue,
		dense_rank() over(order by sum(sl.sales_amount) desc) as "Rank_product"
	from
		gold.sales sl
	left join 
gold.products pd 
on
		sl.product_key = pd.product_key
	group by
		1) top_revenue
where
	"Rank_product" <= 5
;
--23.What are the 5 worst-performing products in terms of sales?
select
	pd.product_name,
	sum(sl.sales_amount) as total_revenue
from
	gold.sales sl
left join 
gold.products pd 
on
	sl.product_key = pd.product_key
group by
	1
order by
	total_revenue asc
limit 5
;
--24.Find the top 10 customers who have generated the highest revenue 
select
	ct.first_name,
	ct.last_name,
	sum(sl.sales_amount) as total_revenue
from
	gold.sales sl
left join 
gold.customers ct 
on
	sl.customer_key = ct.customer_key
group by
	1,
	2
order by
	total_revenue desc
limit 10
;
--25.The 3 customers with the fewest orders placed
select
	ct.customer_key,
	ct.first_name,
	ct.last_name,
	count(distinct sl.order_number) as total_order
from
	gold.customers ct
left join
gold.sales sl
on
	ct.customer_key = sl.customer_key
group by
	1,
	2,
	3
order by
	total_order asc
limit 3
;
